class English():
	def __init__(self):
		self.lang = {

			'title':"Title: ",
			'views':"Views: ",
			'owner':"Owner: ",
			'publish_date':"Publish date: ",
			'author':"Author: ",
			'length':"Length: ",
			'download':"Download",
			'download_queue':"Download queue",
			'download_mode':"Please choose a download mode...",
			'valid_url':"Please provide a valid URL...",
			'url':"URL of the",
			'download_cancel':"Download cancel.",
			'download_folder':"Choose a folder to store your downloads",
			'folder_files':"Your files are in the folder",
			'settings':"Settings",
			'general_settings':"General settings",
			'interface':"Interface",
			'software':"Software",
			'download_path':"Download path (click on the path to edit it):",
			'browse':"Browse...",
			'automatic_updates':"Automatic updates :",
			'yes':"Yes",
			'no':"No",
			'information':"Information",
			'info_settings':"Installing an update will reset the software to its default settings.",
			'save_change':"Save changes",
			'credits':"Credits",
			'developper':"Developper: ",
			'date':"Date: ",
			'message':"Message: ",
			'message_credits':"Thank you for using Mensible :)",
			'changelog':"Changelog",
			'no_internet_changelog':"Please check your internet connection to get the most recent changelog",
			'shutdown':"Shutdown",
			'help':"Help",
			'title_software':"● YouTube & Spotify downloader ●",
			'disclaimer_software':" by ",
			'download_youtube':"Download from YouTube",
			'download_spotify':"Download from Spotify",
			'download_audio':"Download only the audio of the video",
			'download_audio_video':"Download the audio and video",
			'download_file':"Download the file from the provided URL",
			'no_download':"There are no downloads in progress...",
			'file_in_folder':"Your files are in the folder",
			'open_explorer':"Open in the file explorer",
			'no_update':"Unavailable",
			'restart_valid_changes':"Restart to take effect",
			'btn_pause':"Pause the download",
			'btn_resume':"Resume download",
			'btn_cancel':"Cancel download",
			'btn_valid':"Confirm download",
			'support_kofi':"Thank you for supporting me in my work :)",
			'light_theme':"Switch the app to light theme",
			'dark_theme':"Switch the app to dark theme",
			'video_disabled':"Video option is disabled for audio downloads",
			'loading_download':"Loading download...",
			'back_to_home':"Back to home",
			'version':"Version: ",
			'e-mail':"E-mail: ",
			'website':"Website: ",
			'update_available':"Update available",
			'open_website':"Open the website in your browser",
			'write_mail':"Write an e-mail to the developer",
			'update_message':"A new version of Mensible is available. Do you want to download it?",
			'form': "Survey",
			'loading': "Loading the window...",
			'video': "video",
			'playlist': "playlist",
			'language': "Languages available for the software:",
			'light': "Light",
			'dark': "Dark",
			'choice_theme': "Choose a theme for the software:",
			'spotify_client_id': "Spotify Customer ID:",
			'spotify_password': "Spotify Secret Client ID:",
			'use_master_key': "Use default master key set",
			'chunk_size': "Size of a download chunk:",
			'bad_spotify_account': "Invalid Spotify account, please visit settings...",
			'block_settings': "Settings are blocked during a download...",
			'folder_error': "The folder does not exist, please visit settings...",
			'quality': "Quality of the video:",
			'quality_not_available': "Quality not available: ",
			'download_cancel': "Download canceled.",
			'spotify_api_error': "Spotify API credentials are not set or invalid...",
			'spotify_preprocessing': "Spotify preprocessing of the track",
		}

class Francais():
	def __init__(self):
		self.lang = {

			'title':"Titre: ",
			'views':"Vues: ",
			'owner':"Propriétaire: ",
			'publish_date':"Date de publication: ",
			'author':"Auteur: ",
			'length':"Durée: ",
			'download':"Télécharger",
			'download_queue':"Queue de téléchargement",
			'download_mode':"Veuillez choisir un mode de téléchargement...",
			'valid_url':"Veuillez fournir un URL valide...",
			'url':"URL de la",
			'download_cancel':"Téléchargement annulé.",
			'download_folder':"Choississez un dossier pour stocker vos téléchargements",
			'folder_files':"Vos fichiers sont dans le dossier",
			'settings':"Paramètres",
			'general_settings':"Paramètres généraux",
			'interface':"Interface",
			'software':"Logiciel",
			'download_path':"Chemin de téléchargement (cliquez sur le chemin pour l'éditer):",
			'browse':"Parcourir...",
			'automatic_updates':"Mises à jour automatiques :",
			'yes':"Oui",
			'no':"Non",
			'information':"Information",
			'info_settings':"L'installation d'une mise à jour réinitialise les paramètres par défaut.",
			'save_change':"Sauvegarder les changements",
			'credits':"Credits",
			'developper':"Développeur: ",
			'date':"Date: ",
			'message':"Message: ",
			'message_credits':"Merci d'utiliser Mensible :)",
			'changelog':"Changelog",
			'no_internet_changelog':"Veuillez vérifier votre connexion Internet pour obtenir le journal des modifications le plus récent.",
			'shutdown':"Arrêt",
			'help':"Aide",
			'title_software':"● Convertisseur YouTube et Spotify ●",
			'disclaimer_software':" par ",
			'download_youtube':"Télécharger depuis YouTube",
			'download_spotify':"Télécharger depuis Spotify",
			'download_audio':"Télécharger seulement l'audio de la vidéo",
			'download_audio_video':"Télécharger l'audio et la vidéo",
			'download_file':"Télécharger le fichier depuis l'URL fourni",
			'no_download':"Il n'y a pas de téléchargement en attente...",
			'file_in_folder':"Vos fichiers sont dans le dossier",
			'open_explorer':"Ouvrir dans l'explorateur de fichier",
			'no_update':"Indisponible",
			'restart_valid_changes':"Redémarrer pour prendre effet",
			'btn_pause':"Mettre sur pause le téléchargement",
			'btn_resume':"Reprendre le téléchargement",
			'btn_cancel':"Annuler le téléchargement",
			'btn_valid':"Confirmer le téléchargement",
			'support_kofi':"Merci de me soutenir dans mon travail :)",
			'light_theme':"Basculer l'application sur le thème clair",
			'dark_theme':"Basculer l'application sur le thème sombre",
			'video_disabled':"L'option vidéo est désactivée pour les téléchargements audio",
			'loading_download':"Chargement du téléchargement...",
			'back_to_home':"Retour à l'accueil",
			'version':"Version: ",
			'e-mail':"E-mail: ",
			'website':"Site web: ",
			'update_available':"Mise à jour disponible",
			'open_website':"Ouvrir le site web dans votre navigateur",
			'write_mail':"Écrire un e-mail au développeur",
			'update_message':"Une nouvelle version de Mensible est disponible. Voulez-vous la télécharger ?",
			'form': "Enquête",
			'loading': "Chargement de la fenêtre...",
			'video': "vidéo",
			'playlist': "playlist",
			'language': "Langues disponibles pour le logiciel:",
			'light': "Clair",
			'dark': "Sombre",
			'choice_theme': "Choisissez un thème pour le logiciel:",
			'spotify_client_id': "ID client Spotify:",
			'spotify_password': "ID client secret Spotify:",
			'use_master_key': "Utiliser l'ensemble de clés maître par défaut",
			'chunk_size': "Taille d'un chunk de téléchargement:",
			'bad_spotify_account': "Compte Spotify invalide, veuillez visiter les paramètres...",
			'block_settings': "Les paramètres sont bloqués pendant un téléchargement...",
			'folder_error': "Le dossier n'existe pas, veuillez visiter les paramètres...",
			'quality': "Qualité de la vidéo:",
			'quality_not_available': "Qualité non disponible: ",
			'download_cancel': "Téléchargement annulé.",
			'spotify_api_error': "Les identifiants de l'API Spotify ne sont pas définis ou invalides...",
			'spotify_preprocessing': "Prétraitement Spotify de la piste",
		}

class Deutsch():
	def __init__(self):
		self.lang = {

			'title':"Titel: ",
			'views':"Ansichten: ",
			'owner':"Eigentümer: ",
			'publish_date':"Datum der Veröffentlichung: ",
			'author':"Autor: ",
			'length':"Dauer: ",
			'download':"Download",
			'download_queue':"Download-Queue",
			'download_mode':"Bitte wählen Sie eine Downloadmethode...",
			'valid_url':"Bitte geben Sie eine gültige URL an...",
			'url':"URL der",
			'download_cancel':"Download abgebrochen.",
			'download_folder':"Wählen Sie einen Ordner, um Ihre Downloads zu speichern",
			'folder_files':"Ihre Dateien befinden sich im Ordner",
			'settings':"Einstellungen",
			'general_settings':"Allgemeine Einstellungen",
			'interface':"Schnittstelle",
			'software':"Software",
			'download_path':"Pfad der Dateien (klicken Sie auf den Pfad, um ihn zu bearbeiten):",
			'browse':"Ändern...",
			'automatic_updates':"automatisches Update :",
			'yes':"Ya",
			'no':"Nein",
			'information':"Information",
			'info_settings':"Eine neue Aktualisierung setzt die Einstellungen auf die Standardwerte.",
			'save_change':"Änderungen speichern",
			'credits':"Credits",
			'developper':"Entwickler: ",
			'date':"Datum: ",
			'message':"Nachricht: ",
			'message_credits':"Danke für die Nutzung von Mensible :)",
			'changelog':"Changelog",
			'no_internet_changelog':"Bitte überprüfen Sie Ihre Internetverbindung, um das aktuellste Änderungsprotokoll zu erhalten.",
			'shutdown':"Stopp",
			'help':"Hilfe",
			'title_software':"● YouTube und Spotify-Downloader ●",
			'disclaimer_software':" von ",
			'download_youtube':"Von YouTube hochladen",
			'download_spotify':"Von Spotify herunterladen",
			'download_audio':"Nur den Ton des Videos herunterladen",
			'download_audio_video':"Audio und Video herunterladen",
			'download_file':"Laden Sie die Datei von der bereitgestellten URL herunter",
			'no_download':"Es gibt keine ausstehenden Downloads...",
			'file_in_folder':"Ihre Dateien befinden sich im Ordner",
			'open_explorer':"Im Datei-Explorer öffnen",
			'no_update':"Nicht verfügbar",
			'restart_valid_changes':"Neustart, um wirksam zu werden",
			'btn_pause':"Den Download pausieren",
			'btn_resume':"Download fortsetzen",
			'btn_cancel':"Download abbrechen",
			'btn_valid':"Den Download bestätigen",
			'support_kofi':"Danke, dass Sie mich bei meiner Arbeit unterstützen :)",
			'light_theme':"Schalten Sie die Anwendung auf das helle Thema um",
			'dark_theme':"Schalten Sie die Anwendung auf das dunkle Thema um",
			'video_disabled':"Die Videooption ist für Audio-Downloads deaktiviert",
			'loading_download':"Download wird geladen...",
			'back_to_home':"Zurück zur Startseite",
			'version':"Version: ",
			'e-mail':"E-Mail: ",
			'website':"Webseite: ",
			'update_available':"Update verfügbar",
			'open_website':"Öffnen Sie die Website in Ihrem Browser",
			'write_mail':"Schreiben Sie eine E-Mail an den Entwickler",
			'update_message':"Eine neue Version von Mensible ist verfügbar. Möchten Sie sie herunterladen?",
			'form': "Umfrage",
			'loading': "Laden des Fensters...",
			'video': "Video",
			'playlist': "Wiedergabeliste",
			'language': "Verfügbare Sprachen für die Software:",
			'light': "Licht",
			'dark': "Dunkel",
			'choice_theme': "Wählen Sie ein Thema für die Software:",
			'spotify_client_id': "Spotify Client ID:",
			'spotify_password': "Spotify Client Secret ID:",
			'use_master_key': "Verwenden Sie den Standard-Master-Schlüsselsatz",
			'chunk_size': "Größe eines Download-Chunks:",
			'bad_spotify_account': "Ungültiges Spotify-Konto, bitte besuchen Sie die Einstellungen...",
			'block_settings': "Die Einstellungen sind während eines Downloads gesperrt...",
			'folder_error': "Der Ordner existiert nicht, bitte besuchen Sie die Einstellungen...",
			'quality': "Qualität des Videos:",
			'quality_not_available': "Qualität nicht verfügbar: ",
			'download_cancel': "Download abgebrochen.",
			'spotify_api_error': "Spotify API-Zugangsdaten sind nicht gesetzt oder ungültig...",
			'spotify_preprocessing': "Spotify-Vorverarbeitung des Titels",
		}

class Spanish():
	def __init__(self):
		self.lang = {

			'title':"Título: ",
			'views':"Vistas: ",
			'owner':"Propietario: ",
			'publish_date':"Fecha de publicación: ",
			'author':"Autor: ",
			'length':"Duración: ",
			'download':"Descargar",
			'download_queue':"Descarga de la cola",
			'download_mode':"Por favor, elija un modo de descarga...",
			'valid_url':"Por favor, proporcione una URL válida...",
			'url':"URL del",
			'download_cancel':"Descarga cancelada.",
			'download_folder':"Elija una carpeta para almacenar sus descargas",
			'folder_files':"Sus archivos están en el",
			'settings':"Parámetros",
			'general_settings':"Parámetros generales",
			'interface':"Interfaz",
			'software':"Software",
			'download_path':"Ruta de descarga (haga clic en la ruta para editarla):",
			'browse':"Editar...",
			'automatic_updates':"Actualizaciones automáticas :",
			'yes':"Sí",
			'no':"No",
			'information':"Información",
			'info_settings':"La instalación de una actualización restablece la configuración por defecto.",
			'save_change':"Guardar los cambios",
			'credits':"Créditos",
			'developper':"Desarrollador: ",
			'date':"Fecha: ",
			'message':"Mensaje: ",
			'message_credits':"Gracias por utilizar Mensible :)",
			'changelog':"Registro de cambios",
			'no_internet_changelog':"Por favor, compruebe su conexión a Internet para ver el registro de cambios más reciente.",
			'shutdown':"Stop",
			'help':"Ayuda",
			'title_software':"● Descargador de YouTube y Spotify ●",
			'disclaimer_software':" por ",
			'download_youtube':"Descargar de YouTube",
			'download_spotify':"Descargar desde Spotify",
			'download_audio':"Descargar sólo el audio del vídeo",
			'download_audio_video':"Descargar audio y vídeo",
			'download_file':"Descargue el archivo desde la URL proporcionada",
			'no_download':"No hay descargas pendientes...",
			'file_in_folder':"Sus archivos están en el",
			'open_explorer':"Abrir en el Explorador de archivos",
			'no_update':"No disponible",
			'restart_valid_changes':"Reinicio para que surta efecto",
			'btn_pause':"Ponga en pausa la descarga",
			'btn_resume':"Descarga de curriculum vitae",
			'btn_cancel':"Cancelar la descarga",
			'btn_valid':"Confirme la descarga",
			'support_kofi':"Gracias por apoyarme en mi trabajo :)",
			'light_theme':"Cambiar el tema de la aplicación al tema claro",
			'dark_theme':"Cambiar el tema de la aplicación al tema oscuro",
			'video_disabled':"La opción de vídeo está desactivada para las descargas de audio",
			'loading_download':"Descarga en curso...",
			'back_to_home':"Volver a la página de inicio",
			'version':"Versión: ",
			'e-mail':"E-mail: ",
			'website':"Sitio web: ",
			'update_available':"Actualización disponible",
			'open_website':"Abrir el sitio web en su navegador",
			'write_mail':"Escriba un correo electrónico al desarrollador",
			'update_message':"Hay una nueva versión de Mensible disponible. ¿Quieres descargarla?",
			'form': "Encuesta",
			'loading': "Cargando la ventana...",
			'video': "Vídeo",
			'playlist': "Lista de repr.",
			'language': "Idiomas disponibles para el software:",
			'light': "Luz",
			'dark': "Oscuro",
			'choice_theme': "Elija un tema para el software:",
			'spotify_client_id': "Spotify Client ID:",
			'spotify_password': "Spotify Client Secret ID:",
			'use_master_key': "Utilice el conjunto de claves maestras predeterminado",
			'chunk_size': "Tamaño de un fragmento de descarga:",
			'bad_spotify_account': "Cuenta de Spotify no válida, por favor visite la configuración...",
			'block_settings': "La configuración está bloqueada durante una descarga...",
			'folder_error': "La carpeta no existe, por favor visite la configuración...",
			'quality': "Calidad del vídeo:",
			'quality_not_available': "Calidad no disponible: ",
			'download_cancel': "Descarga cancelada.",
			'spotify_api_error': "Las credenciales de la API de Spotify no están configuradas o son inválidas...",
			'spotify_preprocessing': "Preprocesamiento de Spotify de la pista",
		}


class Italiano():
	def __init__(self):
		self.lang = {

			'title':"Titolo: ",
			'views':"Visualizzazioni: ",
			'owner':"Proprietario: ",
			'publish_date':"Data di pubblicazione: ",
			'author':"Autore: ",
			'length':"Lunghezza: ",
			'download':"Scarica",
			'download_queue':"Coda di download",
			'download_mode':"Seleziona la modalità di download...",
			'valid_url':"Inserisci un URL valido...",
			'url':"URL",
			'download_cancel':"Download annullato.",
			'download_folder':"Seleziona una cartella per memorizzare i tuoi download",
			'folder_files':"I tuoi file sono nella cartella",
			'settings':"Impostazioni",
			'general_settings':"Impostazioni generali",
			'interface':"Interfaccia",
			'software':"Software",
			'download_path':"Percorso di download (fare clic sul percorso per modificare):",
			'browse':"Modifica...",
			'automatic_updates':"Aggiornamenti automatici: ",
			'yes':"Sì",
			'no':"No",
			'information':"Informazioni",
			'info_settings':"L'installazione degli aggiornamenti ripristinerà le impostazioni predefinite.",
			'save_change':"Salva le modifiche",
			'credits':"Crediti",
			'developper':"Sviluppatore: ",
			'date':"Data: ",
			'message':"Messaggio: ",
			'message_credits':"Grazie per aver utilizzato Mensible :)",
			'changelog':"Registro delle modifiche",
			'no_internet_changelog':"Controlla la tua connessione Internet per visualizzare l'elenco delle modifiche più recenti.",
			'shutdown':"Stop",
			'help':"Aiuto",
			'title_software':"● Downloader di YouTube e Spotify ●",
			'disclaimer_software':" di ",
			'download_youtube':"Scarica da YouTube",
			'download_spotify':"Scarica da Spotify",
			'download_audio':"Scarica solo l'audio del video",
			'download_audio_video':"Scarica audio e video",
			'download_file':"Scarica il file dall'URL fornito",
			'no_download':"Nessun file da scaricare...",
			'file_in_folder':"I tuoi file sono nella cartella",
			'open_explorer':"Apri nella cartella",
			'no_update':"Non disponibile",
			'restart_valid_changes':"Riavvia per rendere effettive le modifiche",
			'btn_pause':"Pausa download",
			'btn_resume':"Riprendi download",
			'btn_cancel':"Annulla download",
			'btn_valid':"Conferma download",
			'support_kofi':"Grazie per il tuo supporto :)",
			'light_theme':"Cambia il tema dell'applicazione in tema chiaro",
			'dark_theme':"Cambia il tema dell'applicazione in tema scuro",
			'video_disabled':"L'opzione video disabilitata per il download dell'audio",
			'loading_download':"Download in corso...",
			'back_to_home':"Torna alla home",
			'version':"Versione: ",
			'e-mail':"E-mail: ",
			'website':"Sito web: ",
			'update_available':"Aggiornamento disponibile",
			'open_website':"Apri il sito web nel browser",
			'write_mail':"Invia una e-mail al sviluppatore",
			'update_message':"Mensible ha una nuova versione disponibile. Vuoi scaricarla?",
			'form': "Sondaggio",
			'loading': "Caricamento finestra...",
			'video': "Video",
			'playlist': "Playlist",
			'language': "Lingue disponibili per il software:",
			'light': "Luce",
			'dark': "Scuro",
			'choice_theme': "Scegli un tema per il software:",
			'spotify_client_id': "Spotify Client ID:",
			'spotify_password': "Spotify Client Secret ID:",
			'use_master_key': "Utilizzare il set di chiavi master predefinito",
			'chunk_size': "Dimensione di un frammento di download:",
			'bad_spotify_account': "Account Spotify non valido, visita le impostazioni...",
			'block_settings': "Le impostazioni sono bloccate durante il download...",
			'folder_error': "La cartella non esiste, visita le impostazioni...",
			'quality': "Qualità del video:",
			'quality_not_available': "Qualità non disponibile: ",
			'download_cancel': "Download annullato.",
			'spotify_api_error': "Le credenziali dell'API Spotify non sono impostate o non sono valide...",
			'spotify_preprocessing': "Preelaborazione Spotify della traccia",
		}


class Chinese():
	def __init__(self):
		self.lang = {

			'title':"标题: ",
			'views':"观看次数: ",
			'owner':"所有者: ",
			'publish_date':"发布日期: ",
			'author':"作者: ",
			'length':"长度: ",
			'download':"下载",
			'download_queue':"下载队列",
			'download_mode':"请选择下载模式...",
			'valid_url':"请输入有效的URL...",
			'url':"URL",
			'download_cancel':"下载已取消。",
			'download_folder':"选择一个文件夹来存储您的下载",
			'folder_files':"您的文件位于",
			'settings':"设置",
			'general_settings':"常规设置",
			'interface':"界面",
			'software':"软件",
			'download_path':"下载路径 (单击路径以编辑):",
			'browse':"编辑...",
			'automatic_updates':"自动更新: ",
			'yes':"是",
			'no':"没有",
			'information':"信息",
			'info_settings':"安装更新将重置默认设置。",
			'save_change':"保存更改",
			'credits':"信用",
			'developper':"开发者: ",
			'date':"日期: ",
			'message':"信息: ",
			'message_credits':"感谢您使用Mensible :)",
			'changelog':"更新日志",
			'no_internet_changelog':"请检查您的互联网连接以获取最新的更改日志。",
			'shutdown':"停止",
			'help':"帮助",
			'title_software':"● YouTube和Spotify下载器 ●",
			'disclaimer_software':" 通过 ",
			'download_youtube':"从YouTube下载",
			'download_spotify':"从Spotify下载",
			'download_audio':"仅下载视频的音频",
			'download_audio_video':"下载音频和视频",
			'download_file':"从提供的URL下载文件",
			'no_download':"没有待下载的文件...",
			'file_in_folder':"您的文件位于",
			'open_explorer':"在文件资源管理器中打开",
			'no_update':"不可用",
			'restart_valid_changes':"重新启动以生效",
			'btn_pause':"暂停下载",
			'btn_resume':"恢复下载",
			'btn_cancel':"取消下载",
			'btn_valid':"确认下载",
			'support_kofi':"感谢您支持我的工作 :)",
			'light_theme':"将应用程序的主题更改为明亮主题",
			'dark_theme':"将应用程序的主题更改为暗主题",
			'video_disabled':"音频下载的视频选项已禁用",
			'loading_download':"下载中...",
			'back_to_home':"返回主页",
			'version':"版本: ",
			'e-mail':"电子邮件: ",
			'website':"网站: ",
			'update_available':"有可用的更新",
			'open_website':"在浏览器中打开网站",
			'write_mail':"向开发人员发送电子邮件",
			'update_message':"Mensible有新版本可用。你想下载吗?",
			'form': "调查",
			'loading': "加载窗口...",
			'video': "视频",
			'playlist': "播放清单",
			'language': "软件可用的语言:",
			'light': "光",
			'dark': "黑暗",
			'choice_theme': "选择软件的主题:",
			'spotify_client_id': "Spotify客户端ID:",
			'spotify_password': "Spotify客户端秘密ID:",
			'use_master_key': "使用默认的主密钥集",
			'chunk_size': "下载块的大小:",
			'bad_spotify_account': "无效的Spotify帐户,请访问设置...",
			'block_settings': "下载期间设置被锁定...",
			'folder_error': "文件夹不存在,请访问设置...",
			'quality': "视频质量:",
			'quality_not_available': "质量不可用: ",
			'download_cancel': "下载已取消。",
			'spotify_api_error': "Spotify API凭据未设置或无效...",
			'spotify_preprocessing': "Spotify预处理音轨",
		}


class Czech():
	def __init__(self):
		self.lang = {

			'title' : "Název: ",
			'views' : "Zobrazení: ",
			'owner' : "Vlastník: ",
			'publish_date' : "Datum publikace: ",
			'author' : "Autor: ",
			'length' : "Délka: ",
			'download' : "Stáhnout",
			'download_queue' : "Fronta ke stažení",
			'download_mode' : "Vyberte režim stahování...",
			'valid_url' : "Zadejte platnou adresu URL...",
			'url' : "URL",
			'download_cancel' : "Stahování zrušeno.",
			'download_folder' : "Vyberte složku pro uložení souborů",
			'folder_files' : "Vaše soubory jsou ve složce",
			'settings' : "Nastavení",
			'general_settings' : "Obecné nastavení",
			'interface' : "Rozhraní",
			'software' : "Software",
			'download_path' : "Cesta ke staženým souborům (kliknutím na cestu ji můžete upravit):",
			'browse' : "Procházet...",
			'automatic_updates' : "Automatické aktualizace: ",
			'yes' : "Ano",
			'no' : "Ne",
			'information' : "Informace",
			'info_settings' : "Instalace aktualizace obnoví výchozí nastavení.",
			'save_change' : "Uložit změny",
			'credits' : "Kredity",
			'developper' : "Vývojář: ",
			'date' : "Datum: ",
			'message' : "Zpráva: ",
			'message_credits' : "Děkujeme, že používáte Mensible :)",
			'changelog' : "Seznam změn",
			'no_internet_changelog' : "Pro získání nejnovějšího seznamu změn zkontrolujte připojení k Internetu.",
			'shutdown' : "Vypnout",
			'help' : "Nápověda",
			'title_software' : "● YouTube a Spotify Downloader ●",
			'disclaimer_software' : " od ",
			'download_youtube' : "Stáhnout z YouTube",
			'download_spotify' : "Stáhnout ze Spotify",
			'download_audio' : "Stáhnout pouze zvuk videa",
			'download_audio_video' : "Stáhnout zvuk a video",
			'download_file' : "Stáhnout soubor z poskytnuté adresy URL",
			'no_download' : "Nejsou k dispozici žádné stahování...",
			'file_in_folder' : "Vaše soubory jsou ve složce",
			'open_explorer' : "Otevřít v Průzkumníku souborů",
			'no_update' : "Není k dispozici",
			'restart_valid_changes' : "Restartujte, aby se změny projevily",
			'btn_pause' : "Pozastavit stahování",
			'btn_resume' : "Pokračovat ve stahování",
			'btn_cancel' : "Zrušit stahování",
			'btn_valid' : "Potvrdit stahování",
			'support_kofi' : "Děkujeme za podporu mé práce :)",
			'light_theme' : "Přepnout aplikaci na světlý motiv",
			'dark_theme' : "Přepnout aplikaci na tmavý motiv",
			'video_disabled' : "Možnost videa je pro zvuková stahování zakázána",
			'loading_download' : "Načítání stahování...",
			'back_to_home' : "Zpět na domovskou stránku",
			'version' : "Verze: ",
			'e-mail' : "E-mail: ",
			'website' : "Webová stránka: ",
			'update_available' : "Je k dispozici aktualizace",
			'open_website' : "Otevřít webovou stránku v prohlížeči",
			'write_mail' : "Napište e-mail vývojáři",
			'update_message' : "Mensible má k dispozici novou verzi. Chcete ji stáhnout?",
			'form' : "Průzkum",
			'loading' : "Načítání okna...",
			'video' : "Video",
			'playlist' : "Seznam skladeb",
			'language' : "Jazyky dostupné pro software:",
			'light' : "Světlo",
			'dark' : "Tmavý",
			'choice_theme' : "Vyberte motiv pro software:",
			'spotify_client_id' : "Spotify Client ID:",
			'spotify_password' : "Spotify Client Secret ID:",
			'use_master_key' : "Použít výchozí sadu hlavních klíčů",
			'chunk_size' : "Velikost stahovacího fragmentu:",
			'bad_spotify_account' : "Neplatný účet Spotify, přejděte do nastavení...",
			'block_settings' : "Nastavení jsou během stahování blokována...",
			'folder_error' : "Složka neexistuje, přejděte do nastavení...",
			'quality' : "Kvalita videa:",
			'quality_not_available' : "Kvalita není k dispozici: ",
			'download_cancel' : "Stahování zrušeno.",
			'spotify_api_error' : "Přístupové údaje k Spotify API nejsou nastaveny nebo jsou neplatné...",
			'spotify_preprocessing' : "Předzpracování Spotify skladby",
		}
